# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('type', models.CharField(choices=[('purchase', 'purchase'), ('sale', 'sale')], max_length=8)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Purchase')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
    ]
