# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20171009_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('sale_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_cgst', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_sgst', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_igst', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_total', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='SalePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_cgst', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_sgst', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_igst', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_total', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Purchase')),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='pid',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
