# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20171009_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='sale_tax',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='saleprice',
            name='sale_tax',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
    ]
