# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20171009_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_cgst',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_sgst',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_gst',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
