# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20171009_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleprice',
            old_name='sale_cgst',
            new_name='sale_gst',
        ),
        migrations.RemoveField(
            model_name='saleprice',
            name='sale_sgst',
        ),
    ]
