# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20171011_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='sale_cgst',
            new_name='sale_gst',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='sale_sgst',
        ),
    ]
