# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20171015_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default=index.models.date_time),
        ),
    ]
